target:
    registry: mycompany.com
    repository: myteam
images:
  - repository: coreos/prometheus-operator
    version: v0.40.0
    source: quay.io
  - repository: jimmidyson/configmap-reload
    version: v0.3.1
    source: docker.i
  - repository: coreos/prometheus-config-reloader
    version: v0.40.0
    source: quay.io
