mirror:
    registry: plexdev.azurecr.io
    repository: pcp
images:
  - repository: nginx
    version: 1.14.2
    origin: docker.io
  - repository: openpolicyagent/gatekeeper
    version: v3.1.0-beta.10
    origin: docker.io
  - repository: kubernetes-ingress-controller/nginx-ingress-controller
    version: 0.32.0
    origin: quay.io
  - repository: coreos/kube-state-metrics
    version: v1.9.5
    origin: quay.io
  - repository: coreos/prometheus-operator
    version: v0.40.0
    origin: quay.io
  - repository: jimmidyson/configmap-reload
    version: v0.3.0
    origin: docker.io
  - repository: coreos/prometheus-config-reloader
    version: v0.40.0
    origin: quay.io
  - repository: consul
    version: 1.7.2
    origin: docker.io
  - repository: prom/node-exporter
    version: v0.18.1
    origin: docker.io
  - repository: grafana/promtail
    version: v0.4.0
    origin: docker.io
  - repository: twistlock/defender
    version: defender_20_04_177
    origin: registry.twistlock.com
    auth:
        username: MY_USER
        password: MY_PASSWORD
  - repository: jettech/kube-webhook-certgen
    version: v1.2.0
    origin: docker.io
  - repository: prom/alertmanager
    version: v0.21.0
    origin: docker.io
  - repository: prom/prometheus
    version: v2.19.2
    origin: docker.io
