target:
    registry: lol.com
images:
  - repository: pcp/nginx
    version: 1.14.2
    source: docker.io
  - repository: pcp/openpolicyagent/gatekeeper
    version: v3.1.0-beta.10
    source: docker.io
  - repository: pcp/kubernetes-ingress-controller/nginx-ingress-controller
    version: 0.32.0
    source: quay.io
  - repository: pcp/coreos/kube-state-metrics
    version: v1.9.5
    source: quay.io
  - repository: pcp/coreos/prometheus-operator
    version: v0.40.0
    source: quay.io
  - repository: pcp/jimmidyson/configmap-reload
    version: v0.3.0
    source: docker.io
  - repository: pcp/coreos/prometheus-config-reloader
    version: v0.40.0
    source: quay.io
  - repository: pcp/consul
    version: 1.7.2
    source: docker.io
  - repository: pcp/prom/node-exporter
    version: v0.18.1
    source: docker.io
  - repository: pcp/grafana/promtail
    version: v0.4.0
    source: docker.io
  - repository: pcp/twistlock/defender
    version: defender_20_04_177
    source: registry.twistlock.com
  - repository: pcp/jettech/kube-webhook-certgen
    version: v1.2.0
    source: docker.io
  - repository: pcp/prom/alertmanager
    version: v0.21.0
    source: docker.io
  - repository: pcp/prom/prometheus
    version: v2.19.2
    source: docker.io
